server:
  host: "localhost"
  port: "8889"

logger:
  path: "log/log.txt"
  level: "debug"

db:
  postgres:
    driver: "postgres"
    dsn:
      host: "localhost"
      port: "5432"
      dbname: "postgres"
      user: "postgres"
      password: "postgres"
      sslmode: "disable"
    maxconns: 10
    minconns: 3
  memory:
    maxsize: 20

repository:
  type: "memory"